import os
import aiohttp
from os import getenv
from dotenv import load_dotenv
    
load_dotenv()
que = {}
admins = {}

API_ID = int(getenv("API_ID", "1755145"))
API_HASH = getenv("API_HASH", "f1933c5fb9c5c7b4fc1240ae36c809df")
BOT_TOKEN = getenv("BOT_TOKEN", "6193728393:AAGIGGl_gGCYgAnRC8uEgkXE1hk3J2ewRXQ")
DURATION_LIMIT = int(getenv("DURATION_LIMIT", "1200"))
STRING_SESSION = getenv("STRING_SESSION", "BQBnw4TWGkRRMzNDAZ_btfdEKD0eAqFIxrs-iscR63uHX6ps5IzA4H-RyYm8ok6KW6Eu2R_iIj3qvW-4cMewePlUv00yGsEzwPfW0KBwNFKDz7J3BDqSXSbmqYXaHAzVFaddBI9uKxliHc5cvhJjEepFAKpQc1wMyIhOA5I4mDT2nnAxIc9tIdxRcHK9-YEzjcqJHG1Na0CC4orhTE9mRJTiZbYKvoEtnMUVDfVNvZFQem2Qh1LPxmgM8pgaklVLbtnq3pHj2xfvJv4MRV8TOx6jgF6qs_a3qoYizvnnv3U1saJm-JIb9nMe9oSoryxv7Z_qhCG2ZM8y7BzFplYOD5HXAAAAAW4qInAA")
COMMAND_PREFIXES = list(getenv("COMMAND_PREFIXES", "/ ! .").split())
SUDO_USERS = list(map(int, getenv("SUDO_USERS", "6136523097").split()))
aiohttpsession = aiohttp.ClientSession()
